gcp_project_id: synapse-477401
gcp_project_number: 502033304287
region: us-east1
github_repo: alexjmiller5/synapse
gmail_sender_email: redacted-usr@gmail.com
gmail_recipient_email: redacted-usr@gmail.com