import os

import yaml

script_dir = os.path.dirname(os.path.abspath(__file__))


def load_yaml(filename, paths):
    for path in paths:
        full_path = os.path.abspath(path)
        if os.path.exists(full_path):
            try:
                with open(full_path, "r") as f:
                    return yaml.safe_load(f) or {}  # Return empty dict if file is empty
            except Exception as e:
                print(f"⚠️ Error loading {filename} at {full_path}: {e}")
    return {}


def apply_env_overrides(databases):
    """Personal-config overrides so the committed yaml can carry generic examples.

    NOTION_FUN_ACTIVITIES_LOCATIONS (comma-separated, e.g. "Boston,NYC,Hometown")
    replaces the fun-activities Location allowlist — same idea as the
    NOTION_<X>_DB_ID overrides in core/secrets.py. Values must still exist as
    options on the live Notion select (hydration intersects with live options).
    """
    raw = os.environ.get("NOTION_FUN_ACTIVITIES_LOCATIONS")
    prop = (
        databases.get("databases", {})
        .get("fun-activities", {})
        .get("properties", {})
        .get("Location")
    )
    if raw and prop is not None:
        prop["allowlist"] = [s.strip() for s in raw.split(",") if s.strip()]
    return databases


DATABASES = apply_env_overrides(
    load_yaml("databases.yaml", [os.path.join(script_dir, "databases.yaml")])
)
PROMPTS = load_yaml("prompts.yaml", [os.path.join(script_dir, "prompts.yaml")])
# {category: {prop_name: stable_prop_id}} — generated by scripts/fetch_property_ids.py.
# Lets Synapse write/hydrate properties by id (rename-safe) while keeping names in
# databases.yaml for the AI. Missing entries fall back to the name (see prop_id).
PROPERTY_IDS = load_yaml("property_ids.yaml", [os.path.join(script_dir, "property_ids.yaml")])
