#!/usr/bin/env python
"""Generate src/core/property_ids.yaml — {category: {prop_name: prop_id}}.

Synapse writes/hydrates Notion properties by their STABLE id (rename-safe), but
keeps human names in databases.yaml (the AI needs them). This snapshots the live
name->id map. Re-run whenever a Notion property is ADDED (a rename alone keeps
working via the stored id).

Run: op run --env-file=.env.tpl -- uv run scripts/fetch_property_ids.py
"""

import os
import sys

import requests
import yaml

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
from core.config import DATABASES  # noqa: E402
from core.secrets import get_db_id  # noqa: E402

NOTION = "https://api.notion.com/v1"
HEADERS = {
    "Authorization": f"Bearer {os.environ['NOTION_INTEGRATION_TOKEN']}",
    "Notion-Version": "2026-03-11",
}
# Non-category DBs Synapse also writes to (mirror _prefetch_db_ids in secrets.py).
HELPER_CATEGORIES = ["logs", "projects", "trips", "notes", "youtube-channels"]
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "core", "property_ids.yaml")


def data_source_id(db_id):
    r = requests.get(f"{NOTION}/databases/{db_id}", headers=HEADERS, timeout=30)
    r.raise_for_status()
    sources = r.json().get("data_sources") or []
    return sources[0]["id"] if sources else None


def prop_map(ds_id):
    r = requests.get(f"{NOTION}/data_sources/{ds_id}", headers=HEADERS, timeout=30)
    r.raise_for_status()
    return {name: p["id"] for name, p in r.json().get("properties", {}).items()}


def main():
    categories = list(DATABASES.get("databases", {}).keys()) + HELPER_CATEGORIES
    out = {}
    for cat in categories:
        db_id = get_db_id(cat)
        if not db_id:
            print(f"  ⚠️ {cat}: no db_id — skipped")
            continue
        try:
            ds = data_source_id(db_id)
            if not ds:
                print(f"  ⚠️ {cat}: no data source — skipped")
                continue
            out[cat] = dict(sorted(prop_map(ds).items()))
            print(f"  ✓ {cat}: {len(out[cat])} properties")
        except Exception as e:
            print(f"  ❌ {cat}: {e}")

    with open(OUT, "w") as f:
        f.write("# Generated by scripts/fetch_property_ids.py — do not edit by hand.\n")
        f.write("# Notion property name -> stable id, per category (rename-safe writes).\n")
        yaml.safe_dump(dict(sorted(out.items())), f, sort_keys=True, allow_unicode=True)
    print(f"\nWrote {len(out)} categories to {os.path.relpath(OUT)}")


if __name__ == "__main__":
    main()
