#!/bin/bash
set -e
#
# Synapse Project - Local Development Setup Script
#
# This script sets up your local shell for development. It:
# 1. Checks dependencies (uv, gcloud, terraform, yq).
# 2. Creates the local terraform.tfvars file if it doesn't exist.
# 3. Ensures your Python virtual environment is set up and synced.
# 4. Checks your GCP "Application Default Credentials" (ADC).
#
# Your Python application code will use the GCP ADC to fetch
# secrets directly from Secret Manager at runtime.
#
# USAGE:
# 1. Make it executable: chmod +x local_setup.sh
# 2. Run it with 'eval': eval $(./local_setup.sh)
#
# The 'eval' is necessary to activate the virtual environment
# in your current shell.
#

CONFIG_FILE="../config.yaml"
TF_VARS_FILE="../infrastructure/terraform.tfvars"
VENV_DIR=".venv"

# --- Helper Functions ---

# Function to check if a command exists
check_command() {
    if ! command -v "$1" &> /dev/null; then
        echo "💥 Error: $1 is not installed." >&2
        echo "Please install $1 and try again." >&2
        exit 1
    fi
}

# Function to read from config.yaml
get_config() {
    yq e ".$1" "$CONFIG_FILE"
}

# --- Setup Functions ---

# 1. Check all required dependencies
check_dependencies() {
    check_command "uv"
    check_command "gcloud"
    check_command "terraform"
    check_command "yq"
}

# 2. Set up local terraform.tfvars
setup_terraform() {
    if [ -f "$TF_VARS_FILE" ]; then
        echo "✅ Terraform variables file already exists at $TF_VARS_FILE."
    else
        echo "🚀 Creating local $TF_VARS_FILE from config..."
        
        # Check if infrastructure directory exists
        if [ ! -d "infrastructure" ]; then
            echo "Error: 'infrastructure' directory not found. Please run this script from the root of your project." >&2
            exit 1
        fi
        
        # Read values from config.yaml
        local project_id
        local region
        local github_repo
        
        project_id=$(get_config "google_cloud_project_id")
        region=$(get_config "region")
        github_repo=$(get_config "github_repo") # Assumes you added this to config.yaml

        if [ -z "$github_repo" ] || [ "$github_repo" == "null" ]; then
            echo "Warning: 'github_repo' not found in $CONFIG_FILE. Using a placeholder." >&2
            github_repo="your-username/your-repo"
        fi

        # Create the terraform.tfvars file
        cat > "$TF_VARS_FILE" << EOF
# This file is for LOCAL DEVELOPMENT only.
# It was auto-generated by local_setup.sh
# DO NOT COMMIT THIS FILE. Add it to .gitignore.

project_id  = "$project_id"
region      = "$region"
github_repo = "$github_repo"
EOF
        
        echo "✅ Created $TF_VARS_FILE."
        echo "IMPORTANT: Make sure '$TF_VARS_FILE' is in your .gitignore file!"
    fi
}

# 3. Set up Python virtual environment
setup_python() {
    if [ ! -d "$VENV_DIR" ]; then
        echo "🚀 Creating Python virtual environment with uv..."
        uv venv
    fi
    
    echo "📦 Syncing Python dependencies with uv..."
    uv sync --quiet
    echo "✅ Python environment is ready."
}

# 4. Check GCP Authentication
check_gcloud_auth() {
    local project_id
    project_id=$(get_config "google_cloud_project_id")
    
    # Check for Application Default Credentials (ADC)
    # This is what your Python client libraries will use.
    local adc_file="$HOME/.config/gcloud/application_default_credentials.json"
    
    if gcloud auth application-default print-access-token &>/dev/null; then
        echo "✅ GCP Application Default Credentials are active."
    else
        echo "⚠️ GCP Application Default Credentials (ADC) not found." >&2
        echo "Your Python code needs these to access GCP services (like Secret Manager)." >&2
        echo "Please run the following command to log in:" >&2
        echo "" >&2
        echo "  gcloud auth application-default login --project=$project_id" >&2
        echo "" >&2
        exit 1 # Exit because the application code will fail
    fi
    
    # Set the project for gcloud commands (good practice)
    gcloud config set project "$project_id" &> /dev/null
}


# --- Main Execution ---

# This script is designed to be run with 'eval', so we print commands
# to stdout for the parent shell to execute.
# We use >&2 (stderr) for status messages so they don't get captured by 'eval'.

main() {
    check_dependencies >&2
    setup_terraform >&2
    setup_python >&2
    check_gcloud_auth >&2
    
    # These commands MUST go to stdout to be captured by eval
    
    # 1. Activate the virtual environment
    echo "source $VENV_DIR/bin/activate"
    
    # 2. Set project ID as an env var (useful for testing, but not for secrets)
    local project_id
    project_id=$(get_config "google_cloud_project_id")
    echo "export GOOGLE_CLOUD_PROJECT=$project_id"

    echo "🎉 Local environment is configured!" >&2
    echo "Python virtual env is active and GCP auth is verified." >&2
    echo "Your application code will now fetch secrets directly." >&2
}

# Run the main function
main